SmirikCourseBundle:
    resource: "@SmirikCourseBundle/Controller/"
    type:     annotation
    prefix:   /

SmirikContentBundle:
    resource: "@SmirikContentBundle/Controller/"
    type:     annotation
    prefix:   /

SmirikQuizBundle:
    resource: "@SmirikQuizBundle/Controller/"
    type:     annotation
    prefix:   /

SmirikAdminBundle:
    resource: "@SmirikAdminBundle/Controller/"
    type:     annotation
    prefix:   /

SmirikContentBundleRouting:
    resource: "@SmirikContentBundle/Resources/config/routing.yml"
    prefix:   /admin/

SmirikAdminBundleRouting:
    resource: "@SmirikAdminBundle/Resources/config/routing.yml"
    prefix:   /admin/

SmirikQuizBundleRouting:
    resource: "@SmirikQuizBundle/Resources/config/routing.yml"
    prefix:   /admin/

SmirikCourseBundleRouting:
    resource: "@SmirikCourseBundle/Resources/config/routing.yml"
    prefix:   /admin/

_imagine:
    resource: .
    type:     imagine

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /fos/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /fos/resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /fos/profile
