jms_security_extra:
    secure_all_services: false
    expressions: true

security:
  providers:
    fos_userbundle:
      id: fos_user.user_provider.username

  encoders:
    FOS\UserBundle\Model\UserInterface: sha512

  firewalls:
    secured_area:
      pattern: ^/.*
      anonymous: true
      form_login:
          provider: fos_userbundle
          csrf_provider: form.csrf_provider
      logout:
        path: /logout
        target: /

  access_control:
      - { path: ^/register, role: ROLE_VKONTAKTE } # This is the route secured with fos_facebook
      - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/admin/, role: ROLE_ADMIN }
      # - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
      # - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
