services:
  lms42_main_menu_builder:
    class: Smirik\CoreBundle\Menu\MainMenuBuilder
    arguments: [@knp_menu.factory, @service_container]

  lms42_main_menu:
    class: Knp\Menu\MenuItem
    factory_service: lms42_main_menu_builder
    factory_method: build
    tags:
      - { name: knp_menu.menu, alias: main }